version: '3.8'

services:
  bot:
    image: trendoff153/example:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 2G